#pragma once
#include "types.h"

namespace ErrNo
{
	typedef enum {
		NotPermitted = 1,
		NoSuchFileDir = 2,
		NoSuchProcess = 3,
		Interrupted = 4,
		IOError = 5,
		DeviceNotConfig = 6,
		ArgsTooBig = 7,
		ExecError = 8,
		BadFd = 9,
	    NoChild = 10,
	    DeadLock = 11,
	    NoMemory = 12,
	    NoAccess = 13,
	    BadAddress = 14,
	    NotBlockDevice = 15,
	    Busy = 16,
	    FileExists = 17,
	    CrossDeviceLink = 18,
	    BadOpForDevice = 19,
	    NotDirectory = 20,
	    IsDirectory = 21,
	    InvalidArg = 22,
	    TooManyFdAll = 23,
	    TooManyFd = 24,
	    BadIoctl = 25,
	    TextBusy = 26,
	    FileTooBig = 27,
	    NoSpaceDevice = 28,
	    BadSeek = 29,
	    ReadOnlyFS = 30,
	    TooManyLinks = 31,
	    BrokenPipe = 32,

	    TryAgain = 35,
	    InProgress = 36,
	    AlreadyInProgress = 37,
	    NotSocket = 38,
	    NeedDestAddr = 39,
	    MsgTooLong = 40,
	    ProtocolWrong = 41,
	    ProtocolUnavail = 42,
	    ProtocolUnsupport = 43,
	    SocketUnsupport = 44,
	    OperationUnsupport = 45,
	    PFUnsupport = 46,
	    AFUnsupport = 47,
	    AddressInUse = 48,
	    AddressUnavail = 49,
	    NetworkDown = 50,
	    NetworkUnreach = 51,
	    NetworkReset = 52,
	    ConnectAbort = 53,
	    ConnectReset = 54,
	    NoBufferSpace = 55,
	    SocketConnected = 56,
	    SocketNotConnected = 57,
	    SocketShutdown = 58,
	    TooManyRefs = 59,

	    TimeOut = 60,
	    ConnectRefused = 61,
	    SymlinkLoop = 62,
	    NameTooLong = 63,
	    HostDown = 64,
	    HostUnreach = 65,
	    DirectoryNotEmpty = 66,
	    TooManyProcesses = 67,
	    TooManyUsers = 68,
	    DiscQuotaExceeded = 69,

		NoLocks = 77,
	    BadExecutable = 85,
	    BadArch = 86,
	    ShlibMismatch = 87,
		BadMachO = 88,
		Canceled = 89
	} Type;
}
